version: '3.6'
services:
  redis:
    image: redis:latest
    container_name: redis
    # restart: always
    volumes:
      - ./dir/redis:/data
    ports: 
      - "6379:6379"

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    # restart: always
    volumes:
      - ./dir/db:/data
    ports: 
      - "27017:27017"

    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: 123